//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsmSpy.Visualizers {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AsmSpy_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AsmSpy_Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AsmSpy.Visualizers.AsmSpy.Resources", typeof(AsmSpy_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  by .
        /// </summary>
        internal static string by {
            get {
                return ResourceManager.GetString("by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}.
        /// </summary>
        internal static string ConsoleVisualizer_Visualize__0_ {
            get {
                return ResourceManager.GetString("ConsoleVisualizer_Visualize__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à     {0}.
        /// </summary>
        internal static string ConsoleVisualizer_VisualizeAssemblyReferenceInfo______0_ {
            get {
                return ResourceManager.GetString("ConsoleVisualizer_VisualizeAssemblyReferenceInfo______0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à   {0}.
        /// </summary>
        internal static string ConsoleVisualizer_VisualizeAssemblyReferenceInfo____0_ {
            get {
                return ResourceManager.GetString("ConsoleVisualizer_VisualizeAssemblyReferenceInfo____0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}.
        /// </summary>
        internal static string ConsoleVisualizer_VisualizeAssemblyReferenceInfo__0_ {
            get {
                return ResourceManager.GetString("ConsoleVisualizer_VisualizeAssemblyReferenceInfo__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Detailing only conflicting assembly references..
        /// </summary>
        internal static string Detailing_only_conflicting_assembly_references {
            get {
                return ResourceManager.GetString("Detailing_only_conflicting_assembly_references", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid AssemblySource.
        /// </summary>
        internal static string Invalid_AssemblySource {
            get {
                return ResourceManager.GetString("Invalid_AssemblySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à , Location: {0}.
        /// </summary>
        internal static string Location_ {
            get {
                return ResourceManager.GetString("Location_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No assemblies files found in directory.
        /// </summary>
        internal static string No_assemblies_files_found_in_directory {
            get {
                return ResourceManager.GetString("No_assemblies_files_found_in_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reference: .
        /// </summary>
        internal static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source: {0}.
        /// </summary>
        internal static string Source_ {
            get {
                return ResourceManager.GetString("Source_", resourceCulture);
            }
        }
    }
}
